name: Build

on: [ push, pull_request ]


concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:
          compiler: gcc
          version: 11

      - name: Build wheels
        uses: "pypa/cibuildwheel@v2.12.0"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl