name: Build

on: [ push, pull_request ]


concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Setup GNU Fortran
        uses: modflowpy/install-gfortran-action@v1

      - name: Build wheels
        uses: "pypa/cibuildwheel@v2.12.0"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl