name: Build

on: [ push, pull_request ]


concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        arch: [ auto64 ]
        build: [ "cp*", "pp*" ]

        include:
          - os: macos-latest
            type: "Universal"
            arch: universal2
            build: "cp*"

          - os: windows-latest
            arch: auto64
            build: "cp*"

          - os: windows-latest
            arch: auto32
            build: "cp{37,38,39}-*"

    steps:
      - uses: actions/checkout@v3

      - name: Setup GNU Fortran
        uses: modflowpy/install-gfortran-action@v1

      - name: Build wheels
        uses: "pypa/cibuildwheel@v2.12.0"
        env:
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_ARCHS: ${{ matrix.arch }}

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl